replicaCount: 3

image:
  repository: #{IMAGE_REPOSITORY}#

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

service:
  type: ClusterIP
  port: 8888

healthCheckPath: "/"

environments:

serviceAccount:
  create: false
  annotations: {}
  name: #{SERVICE_ACCOUNT}#

ingress:

  internalIngress:
    enabled: true
    pathType: ImplementationSpecific
    annotations:
      kubernetes.io/ingress.class: #{INTERNAL_INGRESS_CLASS}#
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt"
    hosts:
      - host: #{INTERNAL_INGRESS_HOST}#
        paths:
          - /
    tls:
      - hosts:
          - #{INTERNAL_INGRESS_HOST}#

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: #{MIN_REPLICAS}#
  maxReplicas: #{MAX_REPLICAS}#
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

minAvailable: 60%
nodeSelector:
  cloud.google.com/gke-nodepool: "inside-pool"
tolerations:
  - key: "node-pool"
    operator: "Equal"
    value: "inside"
    effect: "NoSchedule"